# Generated by Django 3.0 on 2019-12-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('sexo', models.CharField(max_length=25)),
                ('direccion', models.TextField()),
                ('carrera', models.CharField(max_length=50)),
            ],
        ),
    ]
